"""added total_enrolled model and imported all models in alembic env

Revision ID: 8bb7cc6df32c
Revises: 2776593b2a0f
Create Date: 2022-05-27 01:16:09.430011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8bb7cc6df32c'
down_revision = '2776593b2a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('DBN', sa.String(), nullable=True),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gender_enrolled',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('category_id', postgresql.UUID(), nullable=True),
    sa.Column('school_id', postgresql.UUID(), nullable=True),
    sa.Column('gender', postgresql.ENUM('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('percent', sa.String(), nullable=True),
    sa.Column('count', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_enrolled',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('category_id', postgresql.UUID(), nullable=True),
    sa.Column('school_id', postgresql.UUID(), nullable=True),
    sa.Column('grade', postgresql.ENUM('grade_k', 'grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', name='grade_enum'), nullable=False),
    sa.Column('count', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_enrolled',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('category_id', postgresql.UUID(), nullable=True),
    sa.Column('school_id', postgresql.UUID(), nullable=True),
    sa.Column('race', postgresql.ENUM('asian', 'black', 'hispanic', name='race_enum'), nullable=False),
    sa.Column('percent', sa.String(), nullable=True),
    sa.Column('count', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('total_enrolled',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('category_id', postgresql.UUID(), nullable=True),
    sa.Column('school_id', postgresql.UUID(), nullable=True),
    sa.Column('count', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('total_enrolled')
    op.drop_table('race_enrolled')
    op.drop_table('grade_enrolled')
    op.drop_table('gender_enrolled')
    op.drop_table('schools')
    op.drop_table('categories')
    # ### end Alembic commands ###
