"""updated chart model

Revision ID: 98dfca618e69
Revises: c13bfe4b51c4
Create Date: 2022-05-29 17:18:31.815562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98dfca618e69'
down_revision = 'c13bfe4b51c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
