"""updated sql models count field to float field

Revision ID: 9e4c3cf5ebd0
Revises: 8bb7cc6df32c
Create Date: 2022-05-28 22:09:03.172835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4c3cf5ebd0'
down_revision = '8bb7cc6df32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
