"""created chart model

Revision ID: c13bfe4b51c4
Revises: 9e4c3cf5ebd0
Create Date: 2022-05-29 14:13:03.464920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13bfe4b51c4'
down_revision = '9e4c3cf5ebd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
